name: Unit Test

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-unit
  cancel-in-progress: true

jobs:
  build:
    name: Unit test
    runs-on: macos-15
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # pin@v6.0.3
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # pin@v1.312.0
        with:
          bundler-cache: true

      - name: Select xcode
        run: xcodes select

      - name: Unit tests
        run: bundle exec fastlane unit

      - name: Archive failure diffs
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7.0.1
        with:
          name: FailureDiffs
          path: FailureDiffs
          retention-days: 1

      - name: Save code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # pin@v7.0.1
        with:
          name: test-output
          path: test_output